---
- hosts: localhost
  connection: local
  become: true

  vars:
    essentials_packages:
      - curl
      - wget
      - git
      - vim
      - htop
      - ufw
      - net-tools
      - iproute2
      - tar
      - lynis
      - rkhunter

  tasks:
    - name: Instalar pacotes essenciais para sistemas Linux
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ essentials_packages }}"

    - name: Aplicar Role de Security Hardening
      include_role:
        name: geerlingguy.security

    - name: Aplicar Role de instalacao de docker
      include_role:
        name: geerlingguy.docker

    - name: Bloquear dispostivos Usb's
      copy:
        dest: /etc/modprobe.d/block_usb.conf
        content: "blacklist usb-storage"
        owner: root
        group: root
        mode: '0644'
      notify: Unload usb-storage

  handlers:
    - name: Unload do modulo de usb's
      modprobe:
        name: usb-storage
        state: absent
      ignore_errors: true # In case a device is currently mounted
