---
- hosts: all
  connection: local
  become: true

  vars:
    essentials_packages:
      - curl
      - wget
      - git
      - vim
      - htop
      - ufw
      - net-tools
      - iproute2
      - tar
    state: present

  tasks:
    - name: Instalar pacotes essenciais para sistemas Linux
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ essentials_packages }}"

    - name: Aplicar Role de Security Hardening
      include_role:
        name: geerlingguy.security

    - name: Aplicar Role de instalacao de docker
      include_role:
        name: geerlingguy.docker
